### ISSUE TITLE
Installation with homebrew

### ISSUE THREAD

**Issue by dellagustin-sap** [juven/maven-bash-completion#103]
Hello, I installed mvn-bash-completion using homebrew (brew install maven-completion).
I don't know if this installation is maintained by you, but after the installation I opened a new terminal and the completion was not working.
Are there follow up steps that should be followed after the installation with homebrew?
I will install it manually for now.

**Comment by dellagustin-sap** [comment]
I tried to setup the completion manually and quickly realized that zsh is not supported (maybe this is obvious somehow, but It may be worth mentioning this in the readme).

The error I observed is (slightly edit to hide my path):
```
bash_completion.bash:260: command not found: complete
bash_completion.bash:261: command not found: complete
bash_completion.bash:262: command not found: complete
```
when I start a new terminal.

**Comment by mosabua** [comment]
The project is called bash completion...  we do not maintain the homebrew package .. 

I would suggest to do brew install bash and change the default shell to bash .. then you are ready to go.

**Comment by dellagustin-sap** [comment]
ok, thanks.
