### ISSUE TITLE
Consider writing a plugin for oh-my-zsh

### ISSUE THREAD

**Issue by cleankod** [juven/maven-bash-completion#69]
I have moved to ZSH with oh-my-zsh and its MVN plugin is not as awesome as your script. I really miss autocompleting of the profiles (among other stuff).

So please consider porting this script to [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) plugin (call it maven, not to conflict with current mvn, or simply overwrite it).

**Comment by juven** [comment]
+1 i'm also using zsh :)

**Comment by mosabua** [comment]
There is maven completion for zsh ... e.g. https://github.com/Echos/maven-zsh-completion/

**Comment by cleankod** [comment]
Thanks @mosabua , I've followed your tip and found this:
https://github.com/zsh-users/zsh-completions
It can be hooked up with [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) as a custom plugin.

**Comment by zygimantus** [comment]
Can you share how to hook it up?
