### ISSUE TITLE
Under which license is maven-bash-completion?

### ISSUE THREAD

**Issue by heapifyman** [juven/maven-bash-completion#71]
I would like to create a [AUR package for ArchLinux](https://aur.archlinux.org/) from your script and it is considered good practice to name the license of code you're using in a AUR package.

Under which license do you distribute the maven-bash-completion script?

**Comment by mosabua** [comment]
I assume Apache License but ulitmately @juven has to decide and update.

**Comment by juven** [comment]
yes apache license, let me update
