### ISSUE TITLE
Does it work on mac el capitan?

### ISSUE THREAD

**Issue by dblanch-at-hoplasoftware** [juven/maven-bash-completion#73]
I don't see any results

**Comment by natros** [comment]
It always worked for me.

**Comment by mhrom** [comment]
I would like to say that there is not enough completion for maven target and goals, there are a plenty of plugins without support. What do you think about to add support for cobertura, wadl and so on?

**Comment by viftodi** [comment]
Hello,
 For a manually installed mvn (Just unzipped it and added it to my path), and with bash-completion installed with brew (which just starts all completion scripts in a folder)

I have downloaded it and it seems to work for now, so I can confirm it works.

**Comment by ivanyang1984** [comment]
i am using mac el capitan, seems doesn't have shopt command which in builtin by bash.

**Comment by mosabua** [comment]
Works on mac with bash shell, which is no longer the default. use brew to install a newer bash than what apple ships.
