### ISSUE TITLE
Provide tagged releases

### ISSUE THREAD

**Issue by mnuessler** [juven/maven-bash-completion#79]
Would it be possible to provide tagged releases?

The [homebrew-completions](https://github.com/Homebrew/homebrew-completions) project contains a homebrew formula for installing the maven bash completion. I recently opened a PR (Homebrew/homebrew-completions#116) to upgrade to the latest commit, but the maintainers would prefer to reference a tagged release instead of a git commit hash.

**Comment by mvitz** [comment]
@juven I tried to update the brew formula to support maven wrapper but for this a Tag is required. Do you see any chance for providing a tag for the current master?

**Comment by mosabua** [comment]
I can make a tag .. what would you need as tag name?

**Comment by mvitz** [comment]
The home-brew project does not care about the format of the version number. For this project a date seems reasonable. Another option would be something like `0.1.0` although I'm not sure if semantic versioning is helpful for this kind of project.

**Comment by mosabua** [comment]
created tag https://github.com/juven/maven-bash-completion/tree/20200420

**Comment by mosabua** [comment]
If you need another in the future, just ping me or file an issue.
