### ISSUE TITLE
Incomplete support for Tomcat

### ISSUE THREAD

**Issue by rchaput** [juven/maven-bash-completion#85]
Hi,

When I press [TAB] twice, the list of completions does not include any of the tomcat plugins (e.g. tomcat, tomcat6, tomcat7). However it does work if I start typing "tom" then [TAB].

Moreover, and this is the most annoying IMHO, the goal "redeploy" is not completed when using "tomcat7" phase.
Adding `|tomcat7:redeploy` in the variable "local plugin_goals_tomcat7" on line 177 seems to solve this second problem, but I can't find a workaround for the first.

Thank you in advance for your answers

**Comment by mosabua** [comment]
First is by design .. the plugins only kick in after three characters .. otherwise its the lifecycle phases  .. which is the more common usage.

**Comment by mosabua** [comment]
Also I added redeploy despite tomcat6/7 being kinda old by now ... hahah
