### ISSUE TITLE
Support for more platforms

### ISSUE THREAD

**Issue by MrIndiaDev** [juven/maven-bash-completion#89]
I need help on creating auto completion on platform like Windows and [MavenHub console](https://cui.mavenhub.org).

**Comment by goostleek** [comment]
I can use the completion script w/o any problems on Win with git-bash. Just follow the [installation](https://github.com/juven/maven-bash-completion#installation) steps. 

In my case I had to create a file `%USERPROFILE%\.bashrc` with content
```bash
. ~/.maven_bash_completion.bash
```
and mvn completion works fine for me.
