### ISSUE TITLE
"mvn dep[TAB]" directly expands to "mvn deploy"

### ISSUE THREAD

**Issue by johnlinp** [juven/maven-bash-completion#90]
## Reproduction steps

Type `mvn dep[TAB]`.

## Expected results

See 2 candidates: `deploy` and `dependency:`.

## Actual results

Directly expands to `mvn deploy`.

**Comment by mosabua** [comment]
This is kinda by design.. up to three characters go for lifecycle phases.. only beyond that plugins kick in if there are overlaps..
